apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mynh3mshk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mynh3mshk-go 
  name: mynh3mshk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mynh3mshk-go 
